### ISSUE TITLE
как насчёт url обработчик, который статусы получает ? :)

### ISSUE THREAD

**Issue by smirnovDm** [daaner/turbosms#2]

**Comment by daaner** [comment]
Не совсем понял вопрос... У ТурбоСМС такое организовано?
Может что-то новое, а я пропустил

**Comment by daaner** [comment]
А, я понял)
На самом деле ТурбоСМСу пофиг что этот обработчик возвращает, хоть труе, хоть 404. Это больше для вас нужно, а у каждого своя логика.
Хочешь - просто отправляй СМС и забей на ответы, хочешь сохраняй в БД и меняй статусы при отправке.
Лично я подхватываю статусы и уведомляю менеджеров что СМС отправлено. Однако 1 из 500 СМС пишет `Сообщение отправлено в мобильную сеть, но ещё не обработан ответ от оператора`
Подробнее тут: https://turbosms.ua/api.html

В любом случае я пока не планирую придумывать логику для ответа, т.к. изначально пакет не знает где уведомление и что с ним делать.
Может в будущем я напишу миграции (для ленивых), которые будут через модель сохранять смс и статусы в БД
